# Valid TOML config file

nat-method="DOCKER"

data-path="/MinerNode/data"
genesis-file="/MinerNode/genesis.json"

network-id="01000001"

pruning-enabled=true  

# Connection related
host-allowlist=["all"]

# P2P related
p2p-host="127.0.0.1"
p2p-port=30313

# RPC related
rpc-http-enabled=true
rpc-http-host="127.0.0.1"
rpc-http-port=8502
rpc-http-api=["ADMIN", "ETH", "NET", "TXPOOL", "WEB3", "DEBUG", "TXPOOL", "TRACE", "PLUGINS"]
rpc-http-cors-origins=["all"]

# ethstats
# ethstats="BootNode:itskba@143.110.249.165:3000"

# Mining
miner-enabled=true
miner-coinbase="0x7168165E3109BC12411fD2138c2a5d8968e51Af1"

# Bootnodes
bootnodes=["enode://4f1ab271f4dbd53b2cb0c8f55daa3d1ec315a7c8f130a09e54979aef41708792b18a903b6d96746fc6c4855459e69625f8a428d387692964f86b6a9d5888f128@143.110.249.165:30311"]