# Valid TOML config file

data-path="/Node-3/data"
genesis-file="/Node-3/genesis.json"

network-id="01000001"

pruning-enabled=true  

# Connection related
host-allowlist=["all"]

# P2P related
p2p-host="127.0.0.1"
p2p-port=30313

# RPC related
rpc-http-enabled=true
rpc-http-host="127.0.0.1"
rpc-http-port=9547
rpc-http-api=["ADMIN", "ETH", "NET", "TXPOOL", "WEB3", "DEBUG", "TXPOOL", "TRACE", "PLUGINS"]
rpc-http-cors-origins=["all"]

# ethstats
ethstats="nodename:secret@host:1234"

# Mining
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

# Bootnodes
bootnodes=["enode://001@123:4567", "enode://002@123:4567", "enode://003@123:4567"]