# Valid TOML config file

nat-method="AUTO"

data-path = "/BootNode/data"
genesis-file = "/BootNode/genesis.json"

network-id = "1000001"

# Connection related
host-allowlist = ["all"]

# P2P related
p2p-host = "127.0.0.1"
p2p-port = 30311

# RPC related
rpc-http-enabled = true
rpc-http-host = "127.0.0.1"
rpc-http-port = "8500"
rpc-http-api = ["ADMIN", "ETH", "NET", "TXPOOL", "WEB3", "DEBUG", "TXPOOL", "TRACE", "PLUGINS"]
rpc-http-cors-origins = ["all"]

# ethstats
ethstats="BootNode:itskba@165.22.209.152:3000"