# Valid TOML config file

data-path="/FullNode/data"
genesis-file="/FullNode/genesis.json"

network-id="01000001"

pruning-enabled=true  

# Connection related
host-allowlist=["all"]

# P2P related
p2p-host="127.0.0.1"
p2p-port=30312

# RPC related
rpc-http-enabled=true
rpc-http-host="127.0.0.1"
rpc-http-port=8501
rpc-http-api=["ADMIN", "ETH", "NET", "TXPOOL", "WEB3", "DEBUG", "TXPOOL", "TRACE", "PLUGINS"]
rpc-http-cors-origins=["all"]

# ethstats
ethstats="${ETH_STATS_URL}"

# Bootnodes
bootnodes=["${BOOT_NODE_ENODE_URL}"]
